language: java
jdk: oraclejdk8
install: true
script: ./gradle/buildViaTravis.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_fd546f631468_key -iv $encrypted_fd546f631468_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/32e7cdf345fb9c05a8d1
    on_success: change
    on_failure: always
    on_start: never
